-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 01:57:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjetoMercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetoMercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoMercado` DEFAULT CHARACTER SET utf8 ;
USE `ProjetoMercado` ;

-- -----------------------------------------------------
-- Table `ProjetoMercado`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMercado`.`Turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `desc_turno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMercado`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMercado`.`Setor` (
  `id_setor` INT NOT NULL AUTO_INCREMENT,
  `nome_setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_setor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMercado`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMercado`.`Funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(45) NOT NULL,
  `idade_funcionario` INT NOT NULL,
  `fk_turno` INT NOT NULL,
  `fk_id_setor` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_Funcionario_Turno_idx` (`fk_turno` ASC) VISIBLE,
  INDEX `fk_Funcionario_Setor2_idx` (`fk_id_setor` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Turno`
    FOREIGN KEY (`fk_turno`)
    REFERENCES `ProjetoMercado`.`Turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Setor2`
    FOREIGN KEY (`fk_id_setor`)
    REFERENCES `ProjetoMercado`.`Setor` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




